Repository codesquad-members-2023/be-java-ladder-max, pull requests merged in 2023-03, with the labels that each got.

#4 [sully] step-1 구현
  .idea/git_toolbox_prj.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/workspace.xml
  README.md
  src/main/java/kr/codesquad/Console.java
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/Main.java
Labels: documentation, step-1

#10 [브루니] 학습계획 정리
  README.md
Labels: documentation

#11 [네모네모] step-1 : 사다리 랜덤 생성 기능 구현
  .idea/misc.xml
  .idea/workspace.xml
  README.md
  build.gradle
  src/main/java/kr/codesquad/Ladder.java
  src/test/java/kr/codesquad/LadderTest.java
Labels: documentation, step-1

#12 [브루니] 사다리 게임 1단계 - 기본 기능 구현
  README.md
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/application/LadderGame.java
  src/main/java/kr/codesquad/domain/Ladder.java
  src/main/java/kr/codesquad/view/InputView.java
  src/main/java/kr/codesquad/view/OutputView.java
Labels: step-1

#14 [만두] 학습계획 작성
  README.md
Labels: documentation

#16 [소나무] Step1 사다리게임 구현 관련 학습계획 작성
  .gitignore
  .idea/gradle.xml
  .idea/misc.xml
  .idea/workspace.xml
  README.md
  src/main/java/kr/codesquad/Application.java
  src/main/java/kr/codesquad/InputView.java
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/Outputview.java
Labels: documentation, step-1

#17 [Joy] step-1 구현
  .idea/uiDesigner.xml
  .idea/workspace.xml
  README.md
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/Main.java
Labels: documentation, step-1, step-2

#18 [위즈] 학습계획 작성
  .gitignore
  .idea/workspace.xml
  README.md
Labels: documentation

#19 [takealook] 미션 2 구현 (step2)
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/Output.java
  src/main/java/kr/codesquad/README.md
Labels: step-2

#20 [ayaan] step-1 구현
  README.md
  src/main/java/kr/codesquad/Input.java
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/Main.java
  src/test/java/StringTest.java
Labels: step-1

#21 [길사] Step1 구현
  .idea/encodings.xml
  .idea/workspace.xml
  README.md
  src/main/java/kr/codesquad/Application.java
  src/main/java/kr/codesquad/InputView.java
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/Main.java
Labels: documentation, step-1

#22 [Jwon] step-1 구현
  .idea/aws.xml
  .idea/encodings.xml
  .idea/misc.xml
  .idea/workspace.xml
  README.md
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/Main.java
Labels: documentation, step-1

#25 [Fia] 학습 계획 제출
  .idea/misc.xml
  .idea/workspace.xml
  README.md
Labels: documentation

#26 [무비] step-1&2 완료
  Ladder/Input.java
  Ladder/Ladder.java
  Ladder/Output.java
  Ladder/RunLadder.java
  Ladder/readme.md
  t
Labels: step-1, step-2

#27 [ggom] 학습계획 작성
  README.md
Labels: documentation

#28 [June] 사다리 게임 1단계 - 기본 기능 구현
  README.md
  src/main/java/kr/codesquad/Controller/LadderController.java
  src/main/java/kr/codesquad/Domain/Ladder.java
  src/main/java/kr/codesquad/Domain/Line.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/Util/LadderMaker.java
  src/main/java/kr/codesquad/View/InputView.java
  src/main/java/kr/codesquad/View/OutputView.java
Labels: step-1

#30 [bean] step-1 구현
  .idea/gradle.xml
  .idea/misc.xml
  .idea/runConfigurations.xml
  .idea/workspace.xml
  README.md
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/LadderGame.java
  src/main/java/kr/codesquad/LadderPart.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/Screen.java
Labels: documentation, step-1, step-2, step-3

#31 [나그] 사다리 게임 1단계 - 기본 기능 구현
  .idea/dbnavigator.xml
  .idea/misc.xml
  .idea/sonarlint/issuestore/index.pb
  .idea/workspace.xml
  README.md
  src/main/java/kr/codesquad/Input.java
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/Output.java
Labels: documentation, step-1

#32 [Albert] 학습 계획
  .gitignore
  .idea/.name
  .idea/aws.xml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/vcs.xml
  .idea/workspace.xml
  README.md
  build.gradle
  src/main/java/kr/codesquad/InputRequest.java
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/LadderController.java
  src/main/java/kr/codesquad/LadderPrinter.java
  src/main/java/kr/codesquad/Main.java
  src/test/java/kr/codesquad/InputRequestTest.java
  src/test/java/kr/codesquad/LadderTest.java
Labels: documentation

#59 [Albert] Step-1 구현
  .gitignore
  .idea/.name
  .idea/aws.xml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/vcs.xml
  .idea/workspace.xml
  README.md
  build.gradle
  src/main/java/kr/codesquad/InputRequest.java
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/LadderController.java
  src/main/java/kr/codesquad/LadderPrinter.java
  src/main/java/kr/codesquad/Main.java
  src/test/java/kr/codesquad/InputRequestTest.java
  src/test/java/kr/codesquad/LadderTest.java
Labels: step-1

#34 [light] Step 1 - 구현
  .idea/gradle.xml
  .idea/misc.xml
  .idea/workspace.xml
  README.md
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  src/main/java/kr/codesquad/Input.java
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/Main.java
Labels: step-1

#36 [TOMMY] step-1 학습 계획
  README.md
Labels: documentation, step-1

#37 [jaja] step-1구현
  Inputer.java
  Ladder.java
  Main.java
  README.md
  TestLadder.java
Labels: documentation, step-1

#38 [Jun] 사다리 게임 1단계 - 기본 기능 구현
  .idea/jpa-buddy.xml
  .idea/misc.xml
  .idea/workspace.xml
  docs/readme.md
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/ladder/InputView.java
  src/main/java/kr/codesquad/ladder/Ladder.java
  src/main/java/kr/codesquad/ladder/LadderGame.java
  src/main/java/kr/codesquad/ladder/OutputView.java
Labels: step-1

#39 [Ape] step-1 구현
  README.md
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/controller/GameController.java
  src/main/java/kr/codesquad/domain/Ladder.java
  src/main/java/kr/codesquad/view/InputView.java
  src/main/java/kr/codesquad/view/OutputView.java
Labels: step-1

#40 [시오] step-1 구현
  .gitignore
  README.md
  src/main/java/kr/codesquad/Application.java
  src/main/java/kr/codesquad/Controller.java
  src/main/java/kr/codesquad/Encoding.java
  src/main/java/kr/codesquad/Input.java
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/LadderLine.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/Output.java
  src/main/java/kr/codesquad/Validation.java
Labels: documentation, step-1

#44 [지안] 주간 계획 작성
  .gitignore
  .idea/.name
  .idea/aws.xml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/vcs.xml
  .idea/workspace.xml
  README.md
  src/main/java/kr/codesquad/Main.java
Labels: documentation

#47 [charlie] Step-1 구현
  .idea/gradle.xml
  .idea/misc.xml
  .idea/uiDesigner.xml
  .idea/workspace.xml
  src/README.md
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/util/InputHandler.java
  src/main/java/kr/codesquad/util/InputOutputManager.java
  src/main/java/kr/codesquad/util/OutputHandler.java
  src/test/java/kr/codesquad/LadderTest.java
Labels: documentation, step-1

#49 [만두] Step-1 구현
  README.md
  src/main/java/kr/codesquad/InputView.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/domain/Ladder.java
  src/main/java/kr/codesquad/view/InputView.java
  src/main/java/kr/codesquad/view/OutputView.java
Labels: step-1

#50 [Jinny] step-1 구현
  .gitignore
  .idea/.name
  .idea/aws.xml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/vcs.xml
  .idea/workspace.xml
  README.md
  gradlew.bat
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/config/LadderConfig.java
  src/main/java/kr/codesquad/controller/GameController.java
  src/main/java/kr/codesquad/domain/LadderMaker.java
  src/main/java/kr/codesquad/message/ErrorMessage.java
  src/main/java/kr/codesquad/util/LadderRandomNumberGenerator.java
  src/main/java/kr/codesquad/util/NumberGenerator.java
  src/main/java/kr/codesquad/view/InputValidator.java
  src/main/java/kr/codesquad/view/InputView.java
  src/main/java/kr/codesquad/view/OutputView.java
Labels: step-1

#51 [길사] Step2 리팩터링
  .idea/uiDesigner.xml
  .idea/workspace.xml
  src/main/java/kr/codesquad/Application.java
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/controller/LadderController.java
  src/main/java/kr/codesquad/model/Ladder.java
  src/main/java/kr/codesquad/view/InputView.java
  src/main/java/kr/codesquad/view/OutputView.java
Labels: step-2

#53 [지안] step-1 구현
  src/mission/controller/Application.java
  src/mission/model/Ladder.java
  src/mission/view/InputView.java
  src/mission/view/OutputView.java
Labels: step-1

#63 [Jeegu] Step 1 - 학습 계획
  README.md
  img.png
Labels: documentation

#42 [June] 사다리 게임 3단계 - 사다리 모양 개선
  README.md
  src/main/java/kr/codesquad/Controller/LadderController.java
  src/main/java/kr/codesquad/Domain/Ladder.java
  src/main/java/kr/codesquad/Domain/Line.java
  src/main/java/kr/codesquad/Domain/User.java
  src/main/java/kr/codesquad/View/InputView.java
  src/main/java/kr/codesquad/View/OutputView.java
Labels: step-3

#62 [Jun] - 3단계 구현
  docs/readme.md
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/ladder/BooleanGenerator.java
  src/main/java/kr/codesquad/ladder/InputView.java
  src/main/java/kr/codesquad/ladder/Ladder.java
  src/main/java/kr/codesquad/ladder/LadderGame.java
  src/main/java/kr/codesquad/ladder/Line.java
  src/main/java/kr/codesquad/ladder/Name.java
  src/main/java/kr/codesquad/ladder/Names.java
  src/main/java/kr/codesquad/ladder/OutputView.java
Labels: step-3

#68 [브루니] 사다리 구현 4단계 - 리팩토링 2
  src/main/java/kr/codesquad/application/LadderGame.java
  src/main/java/kr/codesquad/domain/Height.java
  src/main/java/kr/codesquad/domain/Ladder.java
  src/main/java/kr/codesquad/domain/LadderLine.java
  src/main/java/kr/codesquad/domain/Participants.java
  src/main/java/kr/codesquad/generator/RandomLineGenerator.java
  src/test/java/kr/codesquad/domain/HeightTest.java
  src/test/java/kr/codesquad/domain/ParticipantsTest.java
  src/test/java/kr/codesquad/generator/RandomLineGeneratorTest.java
Labels: step-4

#69 [Joy] step-3 구현
  .idea/workspace.xml
  README.md
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/Ladder2.java
  src/main/java/kr/codesquad/Main2.java
  src/main/java/kr/codesquad/Player.java
  src/main/java/kr/codesquad/PrintLadder.java
Labels: step-3

#70 [감귤] 미션 1 구현
  ladder/.idea/.gitignore
  ladder/.idea/misc.xml
  ladder/.idea/modules.xml
  ladder/.idea/vcs.xml
  ladder/src/.idea/misc.xml
  ladder/src/.idea/workspace.xml
  ladder/src/Application.java
  ladder/src/UserInput.java
  ladder/src/ladderController.java
  src/main/java/kr/codesquad/.idea/workspace.xml
Labels: step-1

#71 [위즈] Step-1 구현
  .idea/workspace.xml
  src/main/java/kr/codesquad/Input.java
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/Output.java
Labels: step-1

#72 [나그] step-2 구현
  .idea/sonarlint/issuestore/0/5/05efc8b1657769a27696d478ded1e95f38737233
  .idea/sonarlint/issuestore/1/e/1e36e4561cf27957a38d2d053d7d6d0efeb50aaf
  .idea/sonarlint/issuestore/a/3/a3c4b5a44eb9cd8bb7e224bd9e7138572b858f43
  .idea/sonarlint/issuestore/index.pb
  .idea/workspace.xml
  README.md
  src/main/java/kr/codesquad/Input.java
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/Output.java
Labels: step-2

#74 [Ape] Step 2 구현
  README.md
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/controller/GameController.java
  src/main/java/kr/codesquad/domain/Ladder.java
  src/main/java/kr/codesquad/view/OutputView.java
Labels: step-2

#76 [소나무] Step2 구현
  .gitignore
  .idea/workspace.xml
  README.md
  src/main/java/kr/codesquad/Application.java
  src/main/java/kr/codesquad/InputView.java
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/Outputview.java
Labels: step-2

#81 [Hana] step-1 구현
  .idea/gradle.xml
  .idea/misc.xml
  .idea/uiDesigner.xml
  .idea/workspace.xml
  README.md
  docs/README.md
  src/main/java/kr/codesquad/InputView.java
  src/main/java/kr/codesquad/LadderController.java
  src/main/java/kr/codesquad/LadderGenerator.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/OutputView.java
Labels: step-1

#82 [시오] step-2 구현
  .gitignore
  .idea/.name
  .idea/aws.xml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/vcs.xml
  .idea/workspace.xml
  Mission1.md
  Mission2.md
  README.md
  gradlew
  gradlew.bat
  src/main/java/kr/codesquad/Ladder.java
Labels: step-2

#83 [네모네모] step-2 구현
  .idea/workspace.xml
  README.md
  img/img_5.png
  src/main/java/kr/codesquad/ConsoleInput.java
  src/main/java/kr/codesquad/InvalidPersonNumber.java
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/LadderGame.java
  src/main/java/kr/codesquad/LadderPartGenerator.java
  src/main/java/kr/codesquad/LadderValidator.java
  src/main/java/kr/codesquad/Main.java
  src/test/java/kr/codesquad/LadderPartGeneratorTest.java
Labels: documentation, step-2

#84 [Fia] 사다리 구현 3단계 - 사다리 모양 개선
  .idea/gradle.xml
  .idea/workspace.xml
  README.md
  build.gradle
  src/main/java/ladder/InputView.java
  src/main/java/ladder/Ladder.java
  src/main/java/ladder/Worker.java
  src/test/java/study/CollectionTest.java
  src/test/java/study/ListTest.java
  src/test/java/study/Point.java
Labels: step-3

#85 [bean] step-2 구현
  .idea/uiDesigner.xml
  .idea/workspace.xml
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/LadderGame.java
  src/main/java/kr/codesquad/LadderGenerator.java
  src/main/java/kr/codesquad/LadderV1.java
  src/main/java/kr/codesquad/LadderV2.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/Screen.java
Labels: step-2

#86 [만두] Step2 구현
  .gitignore
  .idea/.name
  .idea/aws.xml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/vcs.xml
  .idea/workspace.xml
  README.md
  src/main/java/kr/codesquad/InputView.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/domain/Ladder.java
  src/main/java/kr/codesquad/view/OutputView.java
Labels: step-2

#87 [Jinny] step-3 구현
  README.md
  src/main/java/kr/codesquad/config/LadderConfig.java
  src/main/java/kr/codesquad/controller/GameController.java
  src/main/java/kr/codesquad/domain/LadderMaker.java
  src/main/java/kr/codesquad/domain/Player.java
  src/main/java/kr/codesquad/domain/Players.java
  src/main/java/kr/codesquad/message/ErrorMessage.java
  src/main/java/kr/codesquad/view/InputValidator.java
  src/main/java/kr/codesquad/view/InputView.java
  src/main/java/kr/codesquad/view/OutputView.java
Labels: step-3

#89 [Albert] Step-5 구현
  .gitignore
  README.md
  src/main/java/kr/codesquad/LadderController.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/domain/Ladder.java
  src/main/java/kr/codesquad/domain/LadderByNames.java
  src/main/java/kr/codesquad/domain/LadderByPeopleCount.java
  src/main/java/kr/codesquad/domain/LadderDrawer.java
  src/main/java/kr/codesquad/domain/SearchInfo.java
  src/main/java/kr/codesquad/domain/SearchType.java
  src/main/java/kr/codesquad/view/InputRequest.java
  src/main/java/kr/codesquad/view/InputView.java
  src/main/java/kr/codesquad/view/LadderPrinter.java
  src/main/java/kr/codesquad/view/OutputView.java
  src/test/java/kr/codesquad/domain/LadderByNamesTest.java
  src/test/java/kr/codesquad/domain/LadderByPeopleCountTest.java
  src/test/java/kr/codesquad/view/InputRequestTest.java
  src/test/java/kr/codesquad/view/InputViewTest.java
  src/test/java/kr/codesquad/view/OutputViewTest.java
Labels: step-5

#90 [지안] Step-2 구현
  .gitignore
  .idea/misc.xml
  .idea/vcs.xml
  README.md
  src/mission/README.md
  src/mission/model/Ladder.java
  src/mission/view/InputView.java
Labels: step-2

#91 [charlie]Step_3 구현
  .gitignore
  .idea/misc.xml
  README.md
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/LadderController.java
  src/main/java/kr/codesquad/LadderGame.java
  src/main/java/kr/codesquad/LadderGameController.java
  src/main/java/kr/codesquad/util/InputHandler.java
  src/main/java/kr/codesquad/util/InputOutputManager.java
  src/main/java/kr/codesquad/util/OutputHandler.java
  src/test/java/kr/codesquad/LadderTest.java
  src/test/java/kr/codesquad/util/InputHandlerTest.java
Labels: step-3

#93 [Joy] step-3 수정
  .idea/workspace.xml
  README.md
  src/main/java/kr/codesquad/Ladder2.java
  src/main/java/kr/codesquad/Player.java
  src/main/java/kr/codesquad/PrintLadder.java
Labels: step-3

#94 [위즈] Step-2 구현
  .idea/uiDesigner.xml
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/LadderGame.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/Output.java
Labels: step-2

#97 [네모네모] step-2 구현 완료
  .gitignore
  .idea/workspace.xml
  README.md
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/LadderGame.java
  src/main/java/kr/codesquad/LadderPartGenerator.java
  src/main/java/kr/codesquad/Main.java
  src/test/java/kr/codesquad/LadderPartGeneratorTest.java
Labels: step-2

#98 [bean] step-3 구현
  .idea/workspace.xml
  build.gradle
  src/main/java/kr/codesquad/LadderGame.java
  src/main/java/kr/codesquad/LadderGenerator.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/PlayerNameLadder.java
  src/main/java/kr/codesquad/PlayerNumberLadder.java
  src/main/java/kr/codesquad/Screen.java
  src/test/java/kr/codesquad/PlayerNameLadderTest.java
  src/test/java/kr/codesquad/ScreenTest.java
Labels: step-3

#99 [Jinny] step-4 일부 구현
  README.md
  src/test/java/kr/codesquad/InputExceptionTest.java
  src/test/java/kr/codesquad/domain/LadderMakerTest.java
  src/test/java/kr/codesquad/domain/PlayersTest.java
  src/test/java/kr/codesquad/util/LadderRandomNumberGeneratorTest.java
Labels: step-4

#100 [jaja] step-3 refactor
  README.md
  src/main/java/kr/codesquad/Inputer.java
  src/main/java/kr/codesquad/Ladder.java
  src/test/java/TestLadder.java
Labels: bug, step-3

#101 [light] Step 3 - 구현
  .gitignore
  README.md
  src/main/java/kr/codesquad/Controller.java
  src/main/java/kr/codesquad/Input2.java
  src/main/java/kr/codesquad/Main2.java
  src/main/java/kr/codesquad/MakeLadder.java
  src/main/java/kr/codesquad/Output.java
  src/main/java/kr/codesquad/User.java
Labels: step-3

#103 Step 3,4,5 코드 수정
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/domain/Ladder.java
  src/main/java/kr/codesquad/domain/LadderByNames.java
  src/main/java/kr/codesquad/domain/LadderByPeopleCount.java
  src/main/java/kr/codesquad/domain/LadderDrawer.java
  src/main/java/kr/codesquad/domain/LadderGame.java
  src/main/java/kr/codesquad/domain/LadderResultCalculator.java
  src/main/java/kr/codesquad/domain/LadderResultRepository.java
  src/main/java/kr/codesquad/domain/LineStateRandomCreator.java
  src/main/java/kr/codesquad/kotlin/InputView.kt
  src/main/java/kr/codesquad/kotlin/Ladder.kt
  src/main/java/kr/codesquad/kotlin/Main.kt
  src/main/java/kr/codesquad/kotlin/OutputView.kt
  src/main/java/kr/codesquad/view/InputView.java
  src/main/java/kr/codesquad/view/OutputView.java
  src/test/java/kr/codesquad/domain/LadderDrawerByPeopleCountTest.java
  src/test/java/kr/codesquad/domain/LadderDrawerTest.java
  src/test/java/kr/codesquad/view/InputViewTest.java
Labels: step-3, step-4, step-5

#104 [길사] step3 구현
  .gitignore
  .idea/.name
  .idea/aws.xml
  .idea/encodings.xml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  .idea/workspace.xml
  README.md
  src/main/java/kr/codesquad/controller/LadderController.java
  src/main/java/kr/codesquad/model/Ladder.java
  src/main/java/kr/codesquad/view/InputView.java
  src/main/java/kr/codesquad/view/OutputView.java
Labels: step-3

#105 [ayaan] step-3 구현
  .gitignore
  README.md
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/Names.java
Labels: step-3

#106 [만두] Step-3 구현
  README.md
  build.gradle
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/domain/Ladder.java
  src/main/java/kr/codesquad/domain/LadderGame.java
  src/main/java/kr/codesquad/domain/LadderHeight.java
  src/main/java/kr/codesquad/domain/RandomRowLineGenerator.java
  src/main/java/kr/codesquad/domain/RowLines.java
  src/main/java/kr/codesquad/domain/User.java
  src/main/java/kr/codesquad/domain/Users.java
  src/main/java/kr/codesquad/view/InputView.java
  src/main/java/kr/codesquad/view/OutputView.java
  src/test/java/kr/codesquad/domain/LadderHeightTest.java
  src/test/java/kr/codesquad/domain/RandomRowLineGeneratorTest.java
  src/test/java/kr/codesquad/domain/UserTest.java
  src/test/java/kr/codesquad/domain/UsersTest.java
Labels: step-3

#107 [지안] step-3 구현
  .gitignore
  .idea/vcs.xml
  src/mission/README.md
  src/mission/controller/Application.java
  src/mission/model/Ladder.java
  src/mission/view/InputView.java
  src/mission/view/OutputView.java
Labels: step-3

#108 [ggom] step-2 구현
  README.md
  src/main/java/kr/codesquad/Ladder.java
Labels: step-2

#109 [시오]Step-3 구현
  README.md
  Step1.md
  Step2.md
  Step3.md
  src/main/java/kr/codesquad/Application.java
  src/main/java/kr/codesquad/Encoding.java
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/Validation.java
  src/main/java/kr/codesquad/controller/Controller.java
  src/main/java/kr/codesquad/model/Ladder.java
  src/main/java/kr/codesquad/model/LadderLine.java
  src/main/java/kr/codesquad/util/Encoding.java
  src/main/java/kr/codesquad/util/Validation.java
  src/main/java/kr/codesquad/view/Input.java
  src/main/java/kr/codesquad/view/Output.java
Labels: step-3

#110 [charlie] step4 구현
  README.md
  build.gradle
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/LadderGame.java
  src/main/java/kr/codesquad/controller/InputOutputController.java
  src/main/java/kr/codesquad/controller/LadderGameController.java
  src/main/java/kr/codesquad/domain/InputParser.java
  src/main/java/kr/codesquad/domain/Ladder.java
  src/main/java/kr/codesquad/domain/LadderLine.java
  src/main/java/kr/codesquad/util/InputHandler.java
  src/main/java/kr/codesquad/util/InputOutputManager.java
  src/main/java/kr/codesquad/util/OutputHandler.java
  src/main/java/kr/codesquad/view/InputHandler.java
  src/main/java/kr/codesquad/view/OutputHandler.java
  src/test/java/kr/codesquad/domain/InputParserTest.java
  src/test/java/kr/codesquad/domain/LadderLineTest.java
  src/test/java/kr/codesquad/util/InputHandlerTest.java
Labels: step-4

#111 [Ape] Step 3 구현
  README.md
  Step-1.md
  Step-2.md
  Step-3.md
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/controller/GameController.java
  src/main/java/kr/codesquad/domain/Ladder.java
  src/main/java/kr/codesquad/domain/Players.java
  src/main/java/kr/codesquad/view/InputView.java
  src/main/java/kr/codesquad/view/OutputView.java
Labels: step-3

#112 [Jwon] step-4 구현
  .idea/uiDesigner.xml
  .idea/workspace.xml
  README.md
  build.gradle
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/domain/Ladder.java
  src/main/java/kr/codesquad/domain/Line.java
  src/main/java/kr/codesquad/domain/RandomUtil.java
  src/main/java/kr/codesquad/view/InputView.java
  src/main/java/kr/codesquad/view/OutputView.java
  src/test/java/InputViewTest.java
  src/test/java/LineTest.java
  src/test/java/OutputViewTest.java
Labels: step-4

#95 [파이] 사다리 게임 1단계 - 기본 기능 구현
  .gitignore
  .idea/gradle.xml
  .idea/workspace.xml
  README.md
  src/main/java/kr/codesquad/InputView.java
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/OutputView.java
Labels: step-1

#114 [시온] step-1 구현
  .gitignore
  .idea/.name
  .idea/aws.xml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/vcs.xml
  .idea/workspace.xml
  README.md
  src/main/java/kr/codesquad/Console.java
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/LadderGame.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/RandomLadderGenerator.java
Labels: step-1

#115 [브루니] 사다리 구현 5단계 - 실행결과 출력
  .gitignore
  .idea/gradle.xml
  .idea/workspace.xml
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/application/LadderGame.java
  src/main/java/kr/codesquad/domain/Input.java
  src/main/java/kr/codesquad/domain/Ladder.java
  src/main/java/kr/codesquad/domain/LadderLine.java
  src/main/java/kr/codesquad/domain/Participant.java
  src/main/java/kr/codesquad/domain/Participants.java
  src/main/java/kr/codesquad/domain/Results.java
  src/main/java/kr/codesquad/view/InputView.java
  src/main/java/kr/codesquad/view/OutputView.java
  src/test/java/kr/codesquad/domain/LadderLineTest.java
Labels: step-5

#117 [위즈] Step-3 구현
  src/main/java/kr/codesquad/Input.java
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/LadderGame.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/Output.java
Labels: step-3

#118 [Hana] Step-2 구현
  .idea/workspace.xml
  docs/README.md
  src/main/java/kr/codesquad/LadderGameController.java
  src/main/java/kr/codesquad/LadderGenerator.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/OutputView.java
Labels: documentation, step-2

#119 [소나무] Step-3 구현
  README.md
  src/main/java/kr/codesquad/Application.java
  src/main/java/kr/codesquad/InputView.java
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/Outputview.java
  src/main/java/kr/codesquad/domain/LadderColumn.java
  src/main/java/kr/codesquad/domain/LadderRow.java
  src/main/java/kr/codesquad/view/InputView.java
  src/main/java/kr/codesquad/view/Outputview.java
Labels: step-3

#120 [네모네모] step-3 구현완료
  README.md
  build.gradle
  img/img_6.png
  img/img_7.png
  src/main/java/kr/codesquad/ConsoleInput.java
  src/main/java/kr/codesquad/ConsoleOutput.java
  src/main/java/kr/codesquad/InvalidNameOfPeopleException.java
  src/main/java/kr/codesquad/InvalidNumberOfMaximumLadderHeightException.java
  src/main/java/kr/codesquad/InvalidNumberOfPeopleException.java
  src/main/java/kr/codesquad/InvalidPersonNumber.java
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/LadderConsoleReader.java
  src/main/java/kr/codesquad/LadderConsoleWriter.java
  src/main/java/kr/codesquad/LadderConverter.java
  src/main/java/kr/codesquad/LadderGame.java
  src/main/java/kr/codesquad/LadderPartGenerator.java
  src/main/java/kr/codesquad/LadderReader.java
  src/main/java/kr/codesquad/LadderValidator.java
  src/main/java/kr/codesquad/LadderWriter.java
  src/main/java/kr/codesquad/Main.java
  src/test/java/kr/codesquad/CollectionTest.java
  src/test/java/kr/codesquad/LadderConsoleReaderTest.java
  src/test/java/kr/codesquad/LadderPartGeneratorTest.java
Labels: documentation, step-3

#121 [시오] step-4 구현
  Step3.md
  Step4.md
  src/main/java/kr/codesquad/controller/Controller.java
  src/main/java/kr/codesquad/domain/Ladder.java
  src/main/java/kr/codesquad/domain/LadderLine.java
  src/main/java/kr/codesquad/domain/Line.java
  src/main/java/kr/codesquad/util/Encoding.java
  src/main/java/kr/codesquad/util/Validation.java
  src/test/java/kr/codesquad/domain/LineTest.java
  src/test/java/kr/codesquad/util/EncodingTest.java
  src/test/java/kr/codesquad/util/ValidationTest.java
Labels: step-4

#122 [Albert] step5 v2
  build.gradle
  gradlew.bat
  src/main/java/kr/codesquad/domain/LadderDrawer.java
  src/main/java/kr/codesquad/domain/LadderGame.java
  src/main/java/kr/codesquad/domain/LadderResultCalculator.java
  src/main/java/kr/codesquad/domain/LadderResultRepository.java
  src/main/java/kr/codesquad/domain/LineInfo.java
  src/main/java/kr/codesquad/domain/LineStateRandomCreator.java
  src/main/java/kr/codesquad/view/InputView.java
  src/main/java/kr/codesquad/view/OutputView.java
  src/test/java/kr/codesquad/domain/LadderDrawerByPeopleCountTest.java
  src/test/java/kr/codesquad/domain/LadderDrawerTest.java
  src/test/java/kr/codesquad/view/InputViewTest.java
Labels: step-5

#123 [만두] Step-4 구현
  README.md
  src/main/java/kr/codesquad/domain/Ladder.java
  src/main/java/kr/codesquad/domain/RandomRowLinesGenerator.java
  src/main/java/kr/codesquad/domain/RowLines.java
  src/main/java/kr/codesquad/domain/User.java
  src/main/java/kr/codesquad/domain/Users.java
  src/main/java/kr/codesquad/view/OutputView.java
  src/test/java/kr/codesquad/domain/LadderHeightTest.java
  src/test/java/kr/codesquad/domain/RandomRowLinesGeneratorTest.java
  src/test/java/kr/codesquad/domain/UserTest.java
  src/test/java/kr/codesquad/domain/UsersTest.java
Labels: step-4

#124 [ayaan] Step-4 구현
  .gitignore
  .idea/gradle.xml
  .idea/workspace.xml
  README.md
  src/main/java/kr/codesquad/Input.java
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/domain/Controller.java
  src/main/java/kr/codesquad/domain/Ladder.java
  src/main/java/kr/codesquad/domain/LadderRow.java
  src/main/java/kr/codesquad/domain/Names.java
  src/main/java/kr/codesquad/view/Input.java
  src/test/java/LadderRowTest.java
  src/test/java/NamesTest.java
Labels: step-4

#125 [Ape] Step 4 구현
  README.md
  Step-4.md
  src/main/java/kr/codesquad/domain/Ladder.java
  src/main/java/kr/codesquad/domain/LadderRow.java
  src/main/java/kr/codesquad/domain/Players.java
  src/main/java/kr/codesquad/view/InputView.java
  src/test/java/kr/codesquad/domain/LadderRowTest.java
  src/test/java/kr/codesquad/domain/PlayersTest.java
Labels: step-4

#127 [jaja] step-3 feature
  README.md
  src/main/java/kr/codesquad/Inputer.java
  src/main/java/kr/codesquad/Ladder.java
Labels: bug, step-3

#129 무비 - Step4 refactoring
  Ladder2/Input.java
  Ladder2/Ladder.java
  Ladder2/Output.java
  Ladder2/RunLadder.java
  Ladder2/domain/Ladder.java
  Ladder2/domain/LadderHeight.java
  Ladder2/domain/LadderRow.java
  Ladder2/domain/Name.java
  Ladder2/domain/Participants.java
  Ladder2/test/LadderRowTest.java
  Ladder2/test/ParticipantsTest.java
  Ladder2/view/Input.java
  Ladder2/view/Output.java
Labels: step-4

#130 [charlie] step-4 v2
  README.md
  src/main/java/kr/codesquad/controller/InputOutputController.java
  src/main/java/kr/codesquad/controller/LadderGameController.java
  src/main/java/kr/codesquad/domain/InputParser.java
  src/main/java/kr/codesquad/domain/LadderHeightValidator.java
  src/main/java/kr/codesquad/domain/LadderLine.java
  src/main/java/kr/codesquad/domain/PlayerValidator.java
  src/main/java/kr/codesquad/view/InputView.java
  src/main/java/kr/codesquad/view/OutputView.java
  src/test/java/kr/codesquad/domain/InputParserTest.java
  src/test/java/kr/codesquad/domain/LadderHeightValidatorTest.java
  src/test/java/kr/codesquad/domain/LadderLineTest.java
  src/test/java/kr/codesquad/domain/PlayerNameValidatorTest.java
Labels: step-4

#131 [Jwon] step-5 구현
  .idea/workspace.xml
  README.md
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/domain/Ladder.java
  src/main/java/kr/codesquad/domain/Line.java
  src/main/java/kr/codesquad/domain/Type.java
  src/main/java/kr/codesquad/view/InputView.java
  src/main/java/kr/codesquad/view/OutputView.java
  src/test/java/InputViewTest.java
  src/test/java/LineTest.java
  src/test/java/OutputViewTest.java
  src/test/java/TypeTest.java
Labels: step-5

#132 [지구] Step-2 구현
  .gitignore
  .idea/uiDesigner.xml
  README.md
  src/main/java/kr/codesquad/Application.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/controller/Controller.java
  src/main/java/kr/codesquad/domain/Ladder.java
  src/main/java/kr/codesquad/domain/LadderLine.java
  src/main/java/kr/codesquad/view/Input.java
  src/main/java/kr/codesquad/view/Output.java
Labels: step-2

#133 [takealook] 미션 5 구현 (step5)
  src/main/java/kr/codesquad/InputCheck.java
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/Names.java
  src/main/java/kr/codesquad/Output.java
  src/main/java/kr/codesquad/OutputView.java
  src/main/java/kr/codesquad/README.md
  src/main/java/kr/codesquad/Results.java
  src/main/java/kr/codesquad/Row.java
Labels: step-5

#134 [보노] step-1 구현
  README.md
  src/main/java/kr/codesquad/Input.java
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/LadderGame.java
  src/main/java/kr/codesquad/LadderLine.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/Output.java
Labels: step-1

#135 [시오] step-4 피드백 반영
  src/main/java/kr/codesquad/controller/Controller.java
  src/main/java/kr/codesquad/domain/Line.java
  src/main/java/kr/codesquad/view/Input.java
  src/main/java/kr/codesquad/view/Output.java
Labels: step-4

#136 [차차] Step1 구현
  .gitignore
  .idea/compiler.xml
  .idea/jarRepositories.xml
  .idea/jpa-buddy.xml
  .idea/misc.xml
  .idea/vcs.xml
  .idea/workspace.xml
  Ladder.iml
  README.md
  settings.gradle
  src/main/java/kr/codesquad/GameMaker.java
  src/main/java/kr/codesquad/InputView.java
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/LadderType.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/OutputView.java
Labels: step-1

#139 [Jwon] step-5 v2(리팩토링)
  .idea/workspace.xml
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/controller/MainController.java
  src/main/java/kr/codesquad/domain/Ladder.java
  src/main/java/kr/codesquad/domain/Line.java
  src/main/java/kr/codesquad/domain/Type.java
  src/main/java/kr/codesquad/view/InputView.java
  src/main/java/kr/codesquad/view/OutputView.java
Labels: step-5

#140 [TOMMY] step-1 구현
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/Main.java
Labels: step-1

#142 [light] Step-4 구현
  .gitignore
  src/main/java/kr/codesquad/ladder/Controller/Controller.java
  src/main/java/kr/codesquad/ladder/Main.java
  src/main/java/kr/codesquad/ladder/domain/Ladder.java
  src/main/java/kr/codesquad/ladder/domain/Line.java
  src/main/java/kr/codesquad/ladder/domain/User.java
  src/main/java/kr/codesquad/ladder/view/Input.java
  src/main/java/kr/codesquad/ladder/view/Output.java
Labels: step-4

#143 [지안] step-4 리팩토링
  .gitignore
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/ladder/Main.java
  src/main/java/kr/ladder/README.md
  src/main/java/kr/ladder/domain/Ladder.java
  src/main/java/kr/ladder/domain/LadderGameController.java
  src/main/java/kr/ladder/view/InputView.java
  src/main/java/kr/ladder/view/OutputView.java
  src/mission/controller/Application.java
  src/mission/model/Ladder.java
Labels: step-4

#145 [Ayaan] Step-5 구현
  .idea/workspace.xml
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/controller/Controller.java
  src/main/java/kr/codesquad/domain/Controller.java
  src/main/java/kr/codesquad/domain/Elements.java
  src/main/java/kr/codesquad/domain/Ladder.java
  src/main/java/kr/codesquad/domain/LadderRow.java
  src/main/java/kr/codesquad/domain/Names.java
  src/main/java/kr/codesquad/util/Validation.java
  src/main/java/kr/codesquad/view/Input.java
  src/test/java/LadderRowTest.java
  src/test/java/NamesTest.java
Labels: step-5

#146 [charlie]step-4 v3
  README.md
  src/main/java/kr/codesquad/controller/InputOutputController.java
  src/main/java/kr/codesquad/controller/LadderGameController.java
  src/main/java/kr/codesquad/domain/LadderHeightValidator.java
  src/main/java/kr/codesquad/domain/LadderLine.java
  src/main/java/kr/codesquad/domain/LinePointsValidator.java
  src/main/java/kr/codesquad/domain/PlayerValidator.java
  src/main/java/kr/codesquad/view/OutputView.java
  src/test/java/kr/codesquad/domain/LadderLineTest.java
  src/test/java/kr/codesquad/domain/PlayerNameValidatorTest.java
Labels: step-4

#147 [sion] step-2 구현
  src/main/java/kr/codesquad/Console.java
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/LadderGame.java
  src/main/java/kr/codesquad/RandomLadderGenerator.java
Labels: step-2

#148 [jaja] step-3 fix
  README.md
  src/main/java/kr/codesquad/Inputer.java
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/Main.java
Labels: bug, documentation, step-3

#151 [만두] Step-5 구현
  README.md
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/domain/Ladder.java
  src/main/java/kr/codesquad/domain/LadderGame.java
  src/main/java/kr/codesquad/domain/LadderHeight.java
  src/main/java/kr/codesquad/domain/LadderResult.java
  src/main/java/kr/codesquad/domain/Result.java
  src/main/java/kr/codesquad/domain/Results.java
  src/main/java/kr/codesquad/domain/RowLines.java
  src/main/java/kr/codesquad/domain/User.java
  src/main/java/kr/codesquad/domain/Users.java
  src/main/java/kr/codesquad/exception/EndGameException.java
  src/main/java/kr/codesquad/exception/ladder/LadderMinHeightException.java
  src/main/java/kr/codesquad/exception/ladder/RowLineDuplicateException.java
  src/main/java/kr/codesquad/exception/ladder/RowLinesMinSizeException.java
  src/main/java/kr/codesquad/exception/result/ResultMaxLengthException.java
  src/main/java/kr/codesquad/exception/result/ResultMinLengthException.java
  src/main/java/kr/codesquad/exception/result/ResultsMinSizeException.java
  src/main/java/kr/codesquad/exception/result/ResultsSizeSameUserCountException.java
  src/main/java/kr/codesquad/exception/user/UserNameMaxLengthException.java
  src/main/java/kr/codesquad/exception/user/UserNameMinLengthException.java
  src/main/java/kr/codesquad/exception/user/UserNameReservedCommand.java
  src/main/java/kr/codesquad/exception/user/UsersDuplicationUserNameException.java
  src/main/java/kr/codesquad/exception/user/UsersMinSizeException.java
  src/main/java/kr/codesquad/util/RandomLadderGenerator.java
  src/main/java/kr/codesquad/view/InputView.java
  src/main/java/kr/codesquad/view/OutputView.java
  src/test/java/kr/codesquad/domain/LadderHeightTest.java
  src/test/java/kr/codesquad/domain/LadderResultTest.java
  src/test/java/kr/codesquad/domain/LadderTest.java
  src/test/java/kr/codesquad/domain/RandomRowLinesGeneratorTest.java
  src/test/java/kr/codesquad/domain/ResultTest.java
  src/test/java/kr/codesquad/domain/ResultsTest.java
  src/test/java/kr/codesquad/domain/RowLinesTest.java
  src/test/java/kr/codesquad/domain/UserTest.java
  src/test/java/kr/codesquad/domain/UsersTest.java
Labels: step-5

#150 [Albert] Step6
  build.gradle
  src/main/java/kr/codesquad/LadderGame.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/domain/InputForm.java
  src/main/java/kr/codesquad/domain/LadderGame.java
  src/main/java/kr/codesquad/domain/LadderGameController.java
  src/main/java/kr/codesquad/domain/LadderResultRepository.java
  src/main/java/kr/codesquad/domain/LadderService.java
  src/main/java/kr/codesquad/domain/LineDelimiterType.java
  src/main/java/kr/codesquad/domain/SearchInfoForm.java
  src/main/java/kr/codesquad/kotlin/InputView.kt
  src/main/java/kr/codesquad/kotlin/Ladder.kt
  src/main/java/kr/codesquad/kotlin/Main.kt
  src/main/java/kr/codesquad/kotlin/OutputView.kt
  src/main/java/kr/codesquad/view/InputView.java
  src/main/java/kr/codesquad/view/OutputView.java
  src/main/resources/application.properties
  src/main/resources/static/component/css/bootstrap.min.css
  src/main/resources/templates/error.html
  src/main/resources/templates/game/search.html
  src/main/resources/templates/game/start.html
  src/test/java/kr/codesquad/view/OutputViewTest.java
  web/WEB-INF/web.xml
Labels: step-6

#152 [위즈] Step-4 구현
  .gitignore
  .idea/gradle.xml
  src/main/java/kr/codesquad/Input.java
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/LadderGame.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/Output.java
  src/main/java/kr/codesquad/domain/Ladder.java
  src/main/java/kr/codesquad/domain/LadderGame.java
  src/main/java/kr/codesquad/domain/Line.java
  src/main/java/kr/codesquad/domain/Validator.java
  src/main/java/kr/codesquad/view/Input.java
  src/main/java/kr/codesquad/view/Output.java
  src/test/java/kr/codesquad/domain/LineTest.java
  src/test/java/kr/codesquad/view/InputTest.java
Labels: step-4

#154 [jaja] step-3 fix
  README.md
  src/main/java/kr/codesquad/Inputer.java
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/Main.java
Labels: bug, step-3

#155 [light] Step 4 - refactor
  README.md
  src/main/java/kr/codesquad/ladder/Controller/Controller.java
  src/main/java/kr/codesquad/ladder/domain/Ladder.java
  src/main/java/kr/codesquad/ladder/domain/Line.java
  src/main/java/kr/codesquad/ladder/domain/User.java
  src/main/java/kr/codesquad/ladder/view/Input.java
  src/main/java/kr/codesquad/ladder/view/Output.java
  src/main/java/kr/codesquad/ladder/view/Validator.java
Labels: step-4

#156 [Ape] Step 4 - 추가 개선
  Step-4.md
  src/main/java/kr/codesquad/controller/GameController.java
  src/main/java/kr/codesquad/domain/Bridge.java
  src/main/java/kr/codesquad/domain/EmptySpace.java
  src/main/java/kr/codesquad/domain/Ladder.java
  src/main/java/kr/codesquad/domain/LadderRow.java
  src/main/java/kr/codesquad/domain/LadderUnit.java
  src/main/java/kr/codesquad/domain/Player.java
  src/main/java/kr/codesquad/domain/PlayerGroup.java
  src/main/java/kr/codesquad/domain/Players.java
  src/main/java/kr/codesquad/view/InputView.java
  src/main/java/kr/codesquad/view/OutputView.java
  src/test/java/kr/codesquad/domain/LadderRowTest.java
  src/test/java/kr/codesquad/domain/PlayerTest.java
  src/test/java/kr/codesquad/domain/PlayersTest.java
Labels: step-4

#157 [보노] step-3 구현
  src/main/java/kr/codesquad/Controller/LadderGame.java
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/LadderGame.java
  src/main/java/kr/codesquad/LadderLine.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/Model/Bar.java
  src/main/java/kr/codesquad/Model/Ladder.java
  src/main/java/kr/codesquad/Model/Line.java
  src/main/java/kr/codesquad/Model/Player.java
  src/main/java/kr/codesquad/Model/PlayerList.java
  src/main/java/kr/codesquad/Output.java
  src/main/java/kr/codesquad/View/Input.java
  src/main/java/kr/codesquad/View/Output.java
Labels: step-3

#159 [네모네모] step-5 일부구현
  README.md
  img/img_7.png
  src/main/java/kr/codesquad/ladder/domain/InvalidCountOfLadderResultException.java
  src/main/java/kr/codesquad/ladder/domain/InvalidLengthOfLadderResultException.java
  src/main/java/kr/codesquad/ladder/domain/Ladder.java
  src/main/java/kr/codesquad/ladder/domain/LadderGame.java
  src/main/java/kr/codesquad/ladder/domain/LadderGenerator.java
  src/main/java/kr/codesquad/ladder/domain/LadderResult.java
  src/main/java/kr/codesquad/ladder/domain/LadderResults.java
  src/main/java/kr/codesquad/ladder/domain/Line.java
  src/main/java/kr/codesquad/ladder/domain/Point.java
  src/main/java/kr/codesquad/ladder/domain/Points.java
  src/main/java/kr/codesquad/ladder/view/LadderConsoleReader.java
  src/main/java/kr/codesquad/ladder/view/LadderConsoleWriter.java
  src/main/java/kr/codesquad/ladder/view/LadderReader.java
  src/main/java/kr/codesquad/ladder/view/LadderWriter.java
  src/test/java/kr/codesquad/ladder/LadderGeneratorConsoleReaderTest.java
  src/test/java/kr/codesquad/ladder/LadderGeneratorTest.java
  src/test/java/kr/codesquad/ladder/MainTest.java
  src/test/java/kr/codesquad/ladder/domain/LadderTest.java
  src/test/java/kr/codesquad/study/StringAddCalculatorTest.java
Labels: documentation, step-5

#160 [Jwon] step-5 v3
  .idea/workspace.xml
  src/main/java/kr/codesquad/domain/Ladder.java
  src/main/java/kr/codesquad/domain/Line.java
  src/test/java/LineTest.java
Labels: step-5

#161 [나그] step3 구현
  .gitignore
  .idea/gradle.xml
  .idea/sonarlint/issuestore/0/5/05efc8b1657769a27696d478ded1e95f38737233
  .idea/sonarlint/issuestore/1/e/1e36e4561cf27957a38d2d053d7d6d0efeb50aaf
  .idea/sonarlint/issuestore/a/3/a3c4b5a44eb9cd8bb7e224bd9e7138572b858f43
  .idea/sonarlint/issuestore/index.pb
  .idea/workspace.xml
  README.md
  src/main/java/kr/codesquad/Input.java
  src/main/java/kr/codesquad/InputHandler.java
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/Line.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/Output.java
  src/main/java/kr/codesquad/Validator.java
Labels: step-3

#162 [지안] step-4 리팩토링 및 학습계획
  .gitignore
  .idea/misc.xml
  README.md
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  src/main/java/kr/ladder/Main.java
  src/main/java/kr/ladder/README.md
  src/main/java/kr/ladder/domain/Ladder.java
  src/main/java/kr/ladder/domain/LadderGameController.java
  src/main/java/kr/ladder/domain/LadderLine.java
  src/main/java/kr/ladder/view/InputView.java
  src/main/java/kr/ladder/view/OutputView.java
Labels: documentation, step-4

#163 [light] Step - 4 test,refactor
  README.md
  src/main/java/kr/codesquad/ladder/Controller/Controller.java
  src/main/java/kr/codesquad/ladder/domain/Ladder.java
  src/main/java/kr/codesquad/ladder/domain/Line.java
  src/main/java/kr/codesquad/ladder/domain/User.java
  src/main/java/kr/codesquad/ladder/view/Input.java
  src/main/java/kr/codesquad/ladder/view/Validator.java
  src/test/java/ladder/LineTest.java
  src/test/java/ladder/ValidatorTest.java
Labels: documentation, step-4

#164 [ayaan] Step-5 refactoring
  README.md
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/controller/Controller.java
  src/main/java/kr/codesquad/domain/Elements.java
  src/main/java/kr/codesquad/domain/Ladder.java
  src/main/java/kr/codesquad/domain/LadderGame.java
  src/main/java/kr/codesquad/domain/Names.java
  src/main/java/kr/codesquad/domain/Results.java
  src/main/java/kr/codesquad/domain/Validator.java
  src/main/java/kr/codesquad/view/Input.java
  src/main/java/kr/codesquad/view/Output.java
  src/test/java/LadderRowTest.java
  src/test/java/NamesTest.java
Labels: step-5

#165 [jaja] step-3 학습계획 추가
  README.md
  src/main/java/kr/codesquad/Ladder.java
Labels: bug, documentation, step-3

#166 [Joy] 학습계획 작성
  .idea/workspace.xml
  README.md
  학습계획.md
Labels: documentation

#167 [시온] step-3 구현 및 주간 학습계획 추가
  README.md
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/LadderGame.java
  src/main/java/kr/codesquad/Player.java
  src/main/java/kr/codesquad/RandomLadderGenerator.java
Labels: documentation, step-3

#168 [bean] step-4
  .idea/inspectionProfiles/Project_Default.xml
  .idea/workspace.xml
  README.md
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/controller/LadderGameController.java
  src/main/java/kr/codesquad/controller/dto/LadderInputDto.java
  src/main/java/kr/codesquad/domain/Ladder.java
  src/main/java/kr/codesquad/domain/LadderLine.java
  src/main/java/kr/codesquad/domain/LadderPart.java
  src/main/java/kr/codesquad/service/LadderGame.java
  src/main/java/kr/codesquad/view/Screen.java
  src/test/java/kr/codesquad/domain/LadderLineTest.java
  src/test/java/kr/codesquad/domain/LadderPartTest.java
  src/test/java/kr/codesquad/view/ScreenTest.java
Labels: step-4

#169 [위즈] Step-5 구현
  README.md
  src/main/java/kr/codesquad/domain/Ladder.java
  src/main/java/kr/codesquad/domain/LadderGame.java
  src/main/java/kr/codesquad/domain/Line.java
  src/main/java/kr/codesquad/domain/Validator.java
  src/main/java/kr/codesquad/view/Input.java
  src/main/java/kr/codesquad/view/Output.java
Labels: step-5

#170 [Fia] 사다리 구현 5단계 - 실행결과 출력
  src/main/java/ladder/domain/Ladder.java
  src/main/java/ladder/domain/LadderGame.java
  src/main/java/ladder/domain/Line.java
  src/main/java/ladder/domain/Players.java
  src/main/java/ladder/domain/Results.java
  src/main/java/ladder/random/RandomManager.java
  src/main/java/ladder/view/View.java
  src/test/java/ladder/domain/LineTest.java
  src/test/java/ladder/domain/PlayersTest.java
Labels: step-5

#171 [Ape] Step-5 구현 1차
  src/main/java/kr/codesquad/controller/GameController.java
  src/main/java/kr/codesquad/domain/Destination.java
  src/main/java/kr/codesquad/domain/DestinationGroup.java
  src/main/java/kr/codesquad/domain/Ladder.java
  src/main/java/kr/codesquad/domain/LadderRow.java
  src/main/java/kr/codesquad/domain/Player.java
  src/main/java/kr/codesquad/domain/PlayerGroup.java
  src/main/java/kr/codesquad/domain/Result.java
  src/main/java/kr/codesquad/domain/ResultGroup.java
  src/main/java/kr/codesquad/view/InputView.java
  src/main/java/kr/codesquad/view/OutputView.java
Labels: step-5

#172 [charlie]step-5 구현
  README.md
  src/main/java/kr/codesquad/controller/InputOutputController.java
  src/main/java/kr/codesquad/controller/LadderGameController.java
  src/main/java/kr/codesquad/domain/ExcutionResultGenerator.java
  src/main/java/kr/codesquad/domain/ExecutionResult.java
  src/main/java/kr/codesquad/domain/Ladder.java
  src/main/java/kr/codesquad/domain/LadderHeight.java
  src/main/java/kr/codesquad/domain/LadderLine.java
  src/main/java/kr/codesquad/domain/PlayerValidator.java
  src/main/java/kr/codesquad/domain/Players.java
  src/main/java/kr/codesquad/domain/RandomLineGenerator.java
  src/main/java/kr/codesquad/domain/Result.java
  src/main/java/kr/codesquad/view/InputView.java
  src/main/java/kr/codesquad/view/OutputView.java
  src/test/java/kr/codesquad/domain/LadderHeightValidatorTest.java
  src/test/java/kr/codesquad/domain/LadderLineTest.java
  src/test/java/kr/codesquad/domain/PlayerNameValidatorTest.java
Labels: step-5

#137 [Hana] 학습계획
  .idea/workspace.xml
  docs/README.md
  docs/img.png
  src/main/java/kr/codesquad/InputView.java
  src/main/java/kr/codesquad/LadderGameController.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/controller/LadderGameController.java
  src/main/java/kr/codesquad/domain/Direction.java
  src/main/java/kr/codesquad/domain/Ladder.java
  src/main/java/kr/codesquad/domain/LadderGenerator.java
  src/main/java/kr/codesquad/domain/Line.java
  src/main/java/kr/codesquad/domain/LineType.java
  src/main/java/kr/codesquad/domain/Player.java
  src/main/java/kr/codesquad/domain/PlayerName.java
  src/main/java/kr/codesquad/domain/Players.java
  src/main/java/kr/codesquad/domain/Point.java
  src/main/java/kr/codesquad/service/LadderGameService.java
  src/main/java/kr/codesquad/strategy/LinkStrategy.java
  src/main/java/kr/codesquad/strategy/RandomLinkStrategy.java
  src/main/java/kr/codesquad/view/InputView.java
  src/main/java/kr/codesquad/view/OutputView.java
Labels: documentation, study plan

#173 [나그]: step 4 학습계획서 작성
  README.md
  Step 1-3.md
  Step4.md
  step3 UML.png
Labels: documentation

#174 [만두] Step5 구현(리팩토링)
  src/main/java/kr/codesquad/domain/LadderGame.java
  src/main/java/kr/codesquad/domain/LadderResult.java
  src/main/java/kr/codesquad/domain/RandomRowLinesGenerator.java
  src/main/java/kr/codesquad/util/RandomLadderGenerator.java
  src/main/java/kr/codesquad/view/OutputView.java
Labels: step-5

#178 [Joy] : step-4 구현
  .idea/workspace.xml
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/Ladder2.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/Main2.java
  src/main/java/kr/codesquad/Player.java
  src/main/java/kr/codesquad/PrintLadder.java
  src/main/java/kr/codesquad/domain/InputLadder.java
  src/main/java/kr/codesquad/domain/Ladder.java
  src/main/java/kr/codesquad/domain/LadderGame.java
  src/main/java/kr/codesquad/domain/Line.java
  src/main/java/kr/codesquad/view/Client.java
  src/main/java/kr/codesquad/view/View.java
  학습계획.md
Labels: step-4

#180 [파이] 사다리 게임 3단계 - 사다리 모양 개선
  README.md
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/LadderController.java
  src/main/java/kr/codesquad/LadderLine.java
  src/main/java/kr/codesquad/OutputView.java
  src/main/java/kr/codesquad/Players.java
Labels: step-3

#182 [시오] Step-4 리팩터링
  README.md
  Step4.md
  Step5.md
  src/main/java/kr/codesquad/Application.java
  src/main/java/kr/codesquad/controller/Controller.java
  src/main/java/kr/codesquad/controller/GameController.java
  src/main/java/kr/codesquad/controller/LadderGame.java
  src/main/java/kr/codesquad/domain/Ladder.java
  src/main/java/kr/codesquad/domain/LadderGenerator.java
  src/main/java/kr/codesquad/domain/LadderLine.java
  src/main/java/kr/codesquad/domain/Line.java
  src/main/java/kr/codesquad/domain/User.java
  src/main/java/kr/codesquad/domain/Users.java
  src/main/java/kr/codesquad/util/Encoding.java
  src/main/java/kr/codesquad/util/Validation.java
  src/main/java/kr/codesquad/view/InputView.java
  src/main/java/kr/codesquad/view/Output.java
  src/main/java/kr/codesquad/view/OutputView.java
  src/test/java/kr/codesquad/domain/LineTest.java
  src/test/java/kr/codesquad/util/EncodingTest.java
  src/test/java/kr/codesquad/util/ValidationTest.java
Labels: step-4

#183 [네모네모] step-5 구현완료
  .gitignore
  README.md
  build.gradle
  img/img.png
  img/img_1.png
  img/img_2.png
  img/img_3.png
  img/img_4.png
  img/img_5.png
  img/img_6.png
  img/img_8.png
  src/main/java/kr/codesquad/ladder/Main.java
  src/main/java/kr/codesquad/ladder/controller/LadderConsoleReaderController.java
  src/main/java/kr/codesquad/ladder/controller/LadderGame.java
  src/main/java/kr/codesquad/ladder/domain/Destination.java
  src/main/java/kr/codesquad/ladder/domain/Destinations.java
  src/main/java/kr/codesquad/ladder/domain/InvalidLengthOfLadderResultException.java
  src/main/java/kr/codesquad/ladder/domain/Ladder.java
  src/main/java/kr/codesquad/ladder/domain/LadderGame.java
  src/main/java/kr/codesquad/ladder/domain/LadderGenerator.java
  src/main/java/kr/codesquad/ladder/domain/LadderResult.java
  src/main/java/kr/codesquad/ladder/domain/LadderResults.java
  src/main/java/kr/codesquad/ladder/domain/Name.java
  src/main/java/kr/codesquad/ladder/domain/Names.java
  src/main/java/kr/codesquad/ladder/domain/Points.java
  src/main/java/kr/codesquad/ladder/exception/InvalidContainOfNamesException.java
  src/main/java/kr/codesquad/ladder/exception/InvalidCountOfLadderResultException.java
  src/main/java/kr/codesquad/ladder/exception/InvalidCountOfPeopleException.java
  src/main/java/kr/codesquad/ladder/exception/InvalidFormatOfDestinationException.java
  src/main/java/kr/codesquad/ladder/exception/InvalidNameFormatOfPeopleException.java
  src/main/java/kr/codesquad/ladder/exception/InvalidNumberOfMinimumLadderHeightException.java
  src/main/java/kr/codesquad/ladder/view/LadderConsoleReader.java
  src/main/java/kr/codesquad/ladder/view/LadderConsoleWriter.java
  src/main/java/kr/codesquad/ladder/view/LadderReader.java
  src/main/java/kr/codesquad/ladder/view/LadderWriter.java
  src/test/java/kr/codesquad/ladder/LadderGeneratorConsoleReaderTest.java
  src/test/java/kr/codesquad/ladder/MainTest.java
  src/test/java/kr/codesquad/ladder/domain/DestinationsTest.java
  src/test/java/kr/codesquad/ladder/domain/LadderGeneratorTest.java
  src/test/java/kr/codesquad/ladder/domain/LadderTest.java
  src/test/java/kr/codesquad/ladder/domain/NameTest.java
  src/test/java/kr/codesquad/ladder/domain/NamesTest.java
  src/test/java/kr/codesquad/ladder/view/LadderConsoleReaderTest.java
  src/test/java/kr/codesquad/study/CollectionTest.java
  src/test/java/kr/codesquad/study/MokitoTest.java
  src/test/java/kr/codesquad/study/StringAddCalculatorTest.java
  src/test/java/kr/codesquad/study/StringTest.java
Labels: step-5

#184 [소나무] Step-4 구현
  README.md
  src/main/java/kr/codesquad/Application.java
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/domain/Ladder.java
  src/main/java/kr/codesquad/domain/LadderColumn.java
  src/main/java/kr/codesquad/domain/LadderRow.java
  src/main/java/kr/codesquad/view/InputView.java
  src/main/java/kr/codesquad/view/OutputView.java
  src/main/java/kr/codesquad/view/Outputview.java
  src/test/java/kr/codesquad/domain/LadderRowTest.java
  src/test/java/kr/codesquad/domain/LadderTest.java
Labels: step-4

#185 [bean] step-5 구현
  .idea/workspace.xml
  README.md
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/controller/LadderGameController.java
  src/main/java/kr/codesquad/controller/dto/LadderOutputDto.java
  src/main/java/kr/codesquad/domain/Direction.java
  src/main/java/kr/codesquad/domain/Ladder.java
  src/main/java/kr/codesquad/domain/LadderLine.java
  src/main/java/kr/codesquad/domain/LadderResult.java
  src/main/java/kr/codesquad/domain/Point.java
  src/main/java/kr/codesquad/service/LadderGame.java
  src/main/java/kr/codesquad/view/Screen.java
  src/test/java/kr/codesquad/view/ScreenTest.java
Labels: step-5

#186 [Joy] step-5 구현
  .idea/workspace.xml
  README.md
  src/main/java/kr/codesquad/domain/InputLadder.java
  src/main/java/kr/codesquad/domain/LadderGame.java
  src/main/java/kr/codesquad/domain/Line.java
  src/main/java/kr/codesquad/domain/Players.java
  src/main/java/kr/codesquad/view/Client.java
  src/main/java/kr/codesquad/view/View.java
  src/test/java/ClientTest.java
  src/test/java/LadderGameTest.java
  src/test/java/LadderTest.java
  src/test/java/LineTest.java
  src/test/java/PlayersTest.java
  학습계획.md
Labels: step-5

#187 [jaja] step-4 refactor
  README.md
  src/main/java/kr/codesquad/InputReader.java
  src/main/java/kr/codesquad/LadderMaker.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/Printer.java
Labels: step-4

#188 [charlie] Step5-v2 구현
  README.md
  src/main/java/kr/codesquad/controller/InputOutputController.java
  src/main/java/kr/codesquad/controller/LadderGameController.java
  src/main/java/kr/codesquad/domain/ExcutionResultGenerator.java
  src/main/java/kr/codesquad/domain/ExecutionResult.java
  src/main/java/kr/codesquad/domain/ExecutionResultGenerator.java
  src/main/java/kr/codesquad/domain/Ladder.java
  src/main/java/kr/codesquad/domain/LadderHeight.java
  src/main/java/kr/codesquad/domain/LadderLine.java
  src/main/java/kr/codesquad/domain/Players.java
  src/main/java/kr/codesquad/domain/RandomLineGenerator.java
  src/main/java/kr/codesquad/domain/Results.java
  src/main/java/kr/codesquad/view/InputView.java
  src/main/java/kr/codesquad/view/OutputView.java
  src/test/java/kr/codesquad/domain/LadderHeightValidatorTest.java
  src/test/java/kr/codesquad/domain/LadderLineTest.java
  src/test/java/kr/codesquad/domain/PlayerNameValidatorTest.java
  src/test/java/study/ArrayListTest.java
  src/test/java/study/CollectionTest.java
Labels: step-5

#189 [Ape] Step 5 코드 리뷰 반영
  README.md
  Step-5.md
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/controller/GameController.java
  src/main/java/kr/codesquad/domain/LadderUnit.java
  src/main/java/kr/codesquad/domain/destination/Destination.java
  src/main/java/kr/codesquad/domain/destination/DestinationGroup.java
  src/main/java/kr/codesquad/domain/ladder/Bridge.java
  src/main/java/kr/codesquad/domain/ladder/EmptySpace.java
  src/main/java/kr/codesquad/domain/ladder/Ladder.java
  src/main/java/kr/codesquad/domain/ladder/LadderRow.java
  src/main/java/kr/codesquad/domain/ladder/LadderUnit.java
  src/main/java/kr/codesquad/domain/player/Player.java
  src/main/java/kr/codesquad/domain/player/PlayerGroup.java
  src/main/java/kr/codesquad/domain/result/Result.java
  src/main/java/kr/codesquad/domain/result/ResultGroup.java
  src/main/java/kr/codesquad/exception/GameProgressException.java
  src/main/java/kr/codesquad/view/InputView.java
  src/main/java/kr/codesquad/view/OutputView.java
  src/test/java/kr/codesquad/domain/LadderRowTest.java
  src/test/java/kr/codesquad/domain/PlayerTest.java
Labels: step-5

#191 [ggom] step-3 작성
  README.md
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/LadderGame.java
  src/main/java/kr/codesquad/Output.java
  src/main/java/kr/codesquad/UserInput.java
Labels: step-3

#192 [Jwon] step-5 리팩토링
  .idea/gradle.xml
  .idea/workspace.xml
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/controller/GameController.java
  src/main/java/kr/codesquad/controller/MainController.java
  src/main/java/kr/codesquad/domain/Ladder.java
  src/main/java/kr/codesquad/domain/Line.java
  src/main/java/kr/codesquad/domain/RandomUtil.java
  src/main/java/kr/codesquad/domain/Type.java
  src/main/java/kr/codesquad/util/Validation.java
  src/main/java/kr/codesquad/view/InputView.java
  src/main/java/kr/codesquad/view/OutputView.java
  src/test/java/InputViewTest.java
  src/test/java/OutputViewTest.java
  src/test/java/TypeTest.java
  src/test/java/ValidationTest.java
Labels: step-5

#193 [나그]: step 4 구현
  .gitignore
  src/main/java/kr/codesquad/Input.java
  src/main/java/kr/codesquad/InputHandler.java
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/Line.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/Output.java
  src/main/java/kr/codesquad/Validator.java
  src/main/java/kr/codesquad/domain/Ladder.java
  src/main/java/kr/codesquad/domain/LadderMaker.java
  src/main/java/kr/codesquad/domain/Line.java
  src/main/java/kr/codesquad/domain/RandomBooleanGenerator.java
  src/main/java/kr/codesquad/view/View.java
  src/test/java/kr/codesquad/LadderTest.java
  src/test/java/kr/codesquad/LineTest.java
  src/test/java/kr/codesquad/RandomBooleanGeneratorTest.java
Labels: step-4

#194 [Joy] step-5 수정
  .idea/workspace.xml
  src/main/java/kr/codesquad/domain/Ladder.java
  src/main/java/kr/codesquad/domain/LadderGame.java
  src/main/java/kr/codesquad/domain/Line.java
  src/main/java/kr/codesquad/domain/Players.java
  src/main/java/kr/codesquad/view/Client.java
  src/main/java/kr/codesquad/view/InputLadder.java
  src/test/java/LadderGameTest.java
  src/test/java/LadderTest.java
  src/test/java/LineTest.java
  src/test/java/PlayersTest.java
Labels: step-5

#195 [bean] step-5
  .idea/workspace.xml
  README.md
  src/main/java/kr/codesquad/controller/LadderGameController.java
  src/main/java/kr/codesquad/controller/dto/LadderInputDto.java
  src/main/java/kr/codesquad/domain/Direction.java
  src/main/java/kr/codesquad/domain/LadderLine.java
  src/main/java/kr/codesquad/domain/LadderResult.java
  src/main/java/kr/codesquad/domain/Point.java
  src/main/java/kr/codesquad/service/LadderGame.java
  src/main/java/kr/codesquad/view/Screen.java
  src/test/java/kr/codesquad/domain/LadderLineTest.java
  src/test/java/kr/codesquad/domain/LadderTest.java
Labels: step-5

#196 [네모네모] step-6 일부구현
  README.md
  build.gradle
  src/main/java/kr/codesquad/ladder/domain/Destinations.java
  src/main/java/kr/codesquad/ladder/domain/DestinationsFactory.java
  src/main/java/kr/codesquad/ladder/domain/Ladder.java
  src/main/java/kr/codesquad/ladder/domain/LadderResults.java
  src/main/java/kr/codesquad/ladder/domain/LadderResultsFactory.java
  src/main/java/kr/codesquad/ladder/domain/Line.java
  src/main/java/kr/codesquad/ladder/domain/Names.java
  src/main/java/kr/codesquad/ladder/domain/NamesFactory.java
  src/main/java/kr/codesquad/ladder/web/Main.java
  src/main/java/kr/codesquad/ladder/web/config/SpringConfig.java
  src/main/java/kr/codesquad/ladder/web/controller/LadderGameController.java
  src/main/resources/application.yml
  src/main/resources/templates/index.html
  src/main/resources/templates/ladder.html
  src/main/resources/templates/ladderForm.html
Labels: step-6

#197 [브루니] step-5 수정
  src/main/java/kr/codesquad/application/LadderGame.java
  src/main/java/kr/codesquad/domain/LadderRideResult.java
  src/test/java/kr/codesquad/generator/RandomLineGeneratorTest.java
Labels: step-5

#198 [지안] step-4 리팩토링
  build.gradle
  gradlew.bat
  src/main/java/kr/ladder/Test.java
  src/main/java/kr/ladder/domain/InputValidation.java
  src/main/java/kr/ladder/domain/Ladder.java
  src/main/java/kr/ladder/domain/LadderGameController.java
  src/main/java/kr/ladder/domain/LadderLine.java
  src/main/java/kr/ladder/view/InputView.java
  src/main/java/kr/ladder/view/OutputView.java
  src/test/java/ladder/LadderLineTest.java
  src/test/java/ladder/PlayerTest.java
Labels: step-4

#200 [light] Step-5 리팩토링
  README.md
  src/main/java/kr/codesquad/ladder/Controller/Controller.java
  src/main/java/kr/codesquad/ladder/domain/Result.java
  src/main/java/kr/codesquad/ladder/domain/ResultLog.java
  src/main/java/kr/codesquad/ladder/domain/User.java
  src/main/java/kr/codesquad/ladder/view/Input.java
  src/main/java/kr/codesquad/ladder/view/Output.java
  src/main/java/kr/codesquad/ladder/view/Validator.java
Labels: step-5

#201 [파이] 사다리 게임 4단계 - 리팩토링 2
  .idea/workspace.xml
  README.md
  src/main/java/kr/codesquad/LadderLine.java
  src/main/java/ladder/Main.java
  src/main/java/ladder/domain/Ladder.java
  src/main/java/ladder/domain/LadderController.java
  src/main/java/ladder/domain/LadderLine.java
  src/main/java/ladder/domain/Players.java
  src/main/java/ladder/domain/RandomGenerator.java
  src/main/java/ladder/view/InputView.java
  src/main/java/ladder/view/OutputView.java
  src/test/java/ladder/domain/PlayersTest.java
  src/test/java/ladder/domain/RandomGeneratorTest.java
Labels: step-4

#202 [Fia] Step-5 피드백 반영
  src/main/java/ladder/domain/Ladder.java
  src/main/java/ladder/domain/LadderGame.java
  src/main/java/ladder/domain/Line.java
  src/main/java/ladder/domain/Player.java
  src/main/java/ladder/domain/Players.java
  src/main/java/ladder/domain/Results.java
  src/main/java/ladder/view/View.java
Labels: step-5

#203 [jaja] step-4 test
  README.md
  src/main/java/kr/codesquad/LadderMaker.java
  src/main/java/kr/codesquad/Printer.java
  src/test/kr/codesquad/InputReaderTest.java
  src/test/kr/codesquad/LadderMakerTest.java
  src/test/kr/codesquad/PrinterTest.java
Labels: step-4

#204 [Ape] Step 6 구현
  README.md
  Step-5.md
  Step-6.md
  src/main/java/kr/codesquad/MainForGUI.form
  src/main/java/kr/codesquad/MainForGUI.java
  src/main/java/kr/codesquad/controller/GUIGameController.java
  src/main/java/kr/codesquad/controller/GameController.java
  src/main/java/kr/codesquad/domain/player/PlayerGroup.java
  src/main/java/kr/codesquad/domain/result/ResultGroup.java
  src/main/java/kr/codesquad/view/InputView.java
  src/main/java/kr/codesquad/view/OutputView.java
Labels: step-6

#206 [나그]: step 5 학습계획서 작성
  Step 5.md
  Step4.md
  step 4 UML.png
Labels: documentation

#208 [네모네모] step-6 구현
  .idea/compiler.xml
  .idea/gradle.xml
  README.md
  img/img.png
  img/img_1.png
  img/img_2.png
  src/main/java/kr/codesquad/ladder/Main.java
  src/main/java/kr/codesquad/ladder/controller/LadderExceptionHandler.java
  src/main/java/kr/codesquad/ladder/controller/LadderGame.java
  src/main/java/kr/codesquad/ladder/controller/LadderGameConsoleController.java
  src/main/java/kr/codesquad/ladder/controller/LadderGameManager.java
  src/main/java/kr/codesquad/ladder/controller/LadderGameWebController.java
  src/main/java/kr/codesquad/ladder/domain/Destination.java
  src/main/java/kr/codesquad/ladder/domain/Destinations.java
  src/main/java/kr/codesquad/ladder/domain/DestinationsFactory.java
  src/main/java/kr/codesquad/ladder/domain/LadderGeneratorFactory.java
  src/main/java/kr/codesquad/ladder/domain/LadderResultsFactory.java
  src/main/java/kr/codesquad/ladder/domain/NamesFactory.java
  src/main/java/kr/codesquad/ladder/exception/InvalidCountOfDestinationsException.java
  src/main/java/kr/codesquad/ladder/exception/InvalidCountOfLadderResultException.java
  src/main/java/kr/codesquad/ladder/exception/InvalidFormatOfDestinationException.java
  src/main/java/kr/codesquad/ladder/view/LadderConsoleReader.java
  src/main/java/kr/codesquad/ladder/view/LadderConsoleWriter.java
  src/main/java/kr/codesquad/ladder/view/LadderWriter.java
  src/main/java/kr/codesquad/ladder/web/Main.java
  src/main/java/kr/codesquad/ladder/web/config/SpringConfig.java
  src/main/java/kr/codesquad/ladder/web/controller/LadderGameController.java
  src/main/resources/templates/index.html
  src/main/resources/templates/ladderForm.html
  src/test/java/kr/codesquad/ladder/MainTest.java
  src/test/java/kr/codesquad/ladder/domain/DestinationsTest.java
Labels: step-6

#209 [jaja] step-4 refactor
  README.md
  src/main/java/kr/codesquad/LadderMaker.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/view/InputView.java
  src/main/java/kr/codesquad/view/OutputView.java
Labels: step-4

#210 [Hana] Step-3 구현
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023_03_17_1_22_AM_[Changes]/shelved.patch
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023_03_17_1_22_AM_[Changes]1/shelved.patch
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023_03_17_1_22_AM__Changes_.xml
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023_03_17_1_22_AM__Changes_1.xml
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023_03_17_3_00_AM_[Changes]/shelved.patch
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023_03_17_3_00_AM__Changes_.xml
  .idea/workspace.xml
  docs/README.md
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/contoroller/LadderGameController.java
  src/main/java/kr/codesquad/controller/LadderGameController.java
  src/main/java/kr/codesquad/domain/Direction.java
  src/main/java/kr/codesquad/domain/Ladder.java
  src/main/java/kr/codesquad/domain/LadderGenerator.java
  src/main/java/kr/codesquad/domain/Line.java
  src/main/java/kr/codesquad/domain/LineType.java
  src/main/java/kr/codesquad/domain/Player.java
  src/main/java/kr/codesquad/domain/PlayerName.java
  src/main/java/kr/codesquad/domain/Players.java
  src/main/java/kr/codesquad/domain/Point.java
  src/main/java/kr/codesquad/service/LadderGameService.java
  src/main/java/kr/codesquad/strategy/LinkStrategy.java
  src/main/java/kr/codesquad/strategy/RandomLinkStrategy.java
  src/main/java/kr/codesquad/view/InputView.java
  src/main/java/kr/codesquad/view/OutputView.java
Labels: step-3

#211 [ light ] Step 6 - 구현_1
  .gitignore
  build.gradle
  src/main/java/kr/codesquad/Application.java
  src/main/java/kr/codesquad/ladder/Controller/WebController.java
  src/main/java/kr/codesquad/ladder/Service/LadderService.java
  src/main/java/kr/codesquad/ladder/domain/Ladder.java
  src/main/java/kr/codesquad/ladder/domain/Line.java
  src/main/java/kr/codesquad/step1_step3/Controller.java
  src/main/java/kr/codesquad/step1_step3/Input.java
  src/main/java/kr/codesquad/step1_step3/Input2.java
  src/main/java/kr/codesquad/step1_step3/Ladder.java
  src/main/java/kr/codesquad/step1_step3/Main.java
  src/main/java/kr/codesquad/step1_step3/Main2.java
  src/main/java/kr/codesquad/step1_step3/MakeLadder.java
  src/main/java/kr/codesquad/step1_step3/Output.java
  src/main/java/kr/codesquad/step1_step3/User.java
  src/main/resources/application.properties
  src/main/resources/static/css/index.css
  src/main/resources/templates/index.html
  src/main/resources/templates/ladder.html
Labels: step-6
